micronaut:
  security:
    authentication: cookie
    token:
      refresh:
        cookie:
          enabled: false
    intercept-url-map:
      - pattern: /**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /**
        http-method: POST
        access:
          - isAnonymous()
graphql:
  graphiql.enabled: true
